config:
  azure-native:location: "canadacentral"
  cst8918-a03-infra:appPath: ../
  cst8918-a03-infra:containerPort: '80'
  cst8918-a03-infra:publicPort: '80'
  cst8918-a03-infra:cpu: '1'
  cst8918-a03-infra:memory: '2'
  cst8918-a03-infra:prefixName: 'cst8918-a03-zhao0201'
  cst8918-a03-infra:imageTag: v0.3.0
  cst8918-a03-infra:weatherApiKey:
    secure: AAABADePs5sf5GvfEHnkE4hrREB127y2nrdbOa3q66wssoNmwFnTaO5tWI3qbYqYfs1ksQUSEtWi3iVyvhKKaw==
